#!/bin/bash

if [ -z "$1" ]; then
	echo "Need the docker network as argument" >&2
	return 1
fi

net=$(docker network ls --quiet --filter name=$1)
if [ $(echo "$net" | wc -l) -ne 1 ]; then
	echo "The docker network $1 can not be found" >&2
	return 1
fi
shift

docker run --rm \
	-i \
	-v /etc/localtime:/etc/localtime:ro \
	-e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
	-e USER -e UID=$(id --user) -e GID=$(id --group) \
	--net $net \
	cell/firefox \
	$@

